### ISSUE TITLE
Is CallReceiver required?

### ISSUE THREAD

**Issue by mnesarco** [oovoodev/Android-SDK-Sample#12]
Hi Guys,

I am learning from this sample. I want to build the minimal 2-participant conference Activity.

There is a Receiver in the manifest listening to phone state (com.oovoo.core.phone.CallReceiver), but can you tell me why is this necessary? or can I remove it?

Thanks a lot.

**Comment by ochornenko** [comment]
Hi,

It is for handling audio route when phone call is happening, you can remove it if you do not care about that.

**Comment by mnesarco** [comment]
Hi, Thanks for your response. 

So it is unnecessary for the conference by itself, but it controls audio coalitions with incoming phone calls. Very nice.

Thanks.
