### ISSUE TITLE
Invalid Parameter

### ISSUE THREAD

**Issue by efvaldez1** [oovoodev/Android-SDK-Sample#13]
Good day , I have downloaded the SDK from your website , then i edited the base url , appid and token . However when i run the app i get "Error:Invalid Parameters" . There should be  "\ " + AppId and " " + AppToken right? what should I do? may I ask some assistance , thanks

// UserSettingsManager
private static final String BASE_BE_URL_DEFAULT = "https://api‐sdk.dev.oovoo.com";
//Manifest
 <meta-data
            android:name="AppId"
            android:value="\ 12349983353940" /> 
        <meta-data
            android:name="AppToken"
            android:value=" MDAx...........0wGQtrf%2FS3OahLw" />

**Comment by eranmalovany** [comment]
hi,

according the information you provide, your App ID include spaces and backslash, please remove : "\ 12349983353940"
please also make sure you copy the all token value from the ooVoo developers website.
let me know if it solve the issue.
