### ISSUE TITLE
Sample app crashes: java.lang.RuntimeException: Fail to connect to camera service

### ISSUE THREAD

**Issue by mydoal** [oovoodev/Android-SDK-Sample#15]
Using SDK 2.0.0.80

Sample app randomly crashes on LG2 Android 4.4.2.

08-09 23:47:18.361  11366-11366/? V/MmsConfig﹕ [isMmsEnabledWhenDataDisabled]exception case5
08-09 23:47:26.711  11413-11442/com.oovoo.sdk.oovoosdksampleshow E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> initCamera  failed = java.lang.RuntimeException: Fail to connect to camera service
08-09 23:47:26.721  11413-11413/com.oovoo.sdk.oovoosdksampleshow W/System.err﹕ java.lang.RuntimeException: Fail to connect to camera service
08-09 23:47:28.231  11762-11762/? V/AudioPolicyManagerBase﹕ mIsSoundException is 1
08-09 23:47:35.191  11890-11890/? V/AudioPolicyManagerBase﹕ mIsSoundException is 1
08-09 23:47:40.911  11985-11985/? V/AudioPolicyManagerBase﹕ mIsSoundException is 1
08-09 23:47:45.461  12071-12071/? V/AudioPolicyManagerBase﹕ mIsSoundException is 1
08-09 23:47:46.171    970-12144/? W/ActivityManager﹕ Exception thrown during pause
    android.os.DeadObjectException
            at android.os.BinderProxy.transact(Native Method)
            at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:660)
            at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:805)
            at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2679)
            at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2545)
            at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2480)
            at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9888)
            at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9775)
            at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10426)
            at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9977)
            at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
08-09 23:47:46.181     970-1652/? W/WindowManager﹕ Failed looking up window
    java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@430fcbf0 does not exist
            at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9067)
            at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9058)
            at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1363)
            at android.os.BinderProxy.sendDeathNotice(Binder.java:504)
            at dalvik.system.NativeStart.run(Native Method)

------------------------

08-10 00:08:23.191  14041-14061/com.oovoo.sdk.oovoosdksampleshow D/ooVooSdkNative﹕ [Debug] 2015-08-10 00:08:23.205 VideoControllerWrap -> OnRemoteVideoStateChanged 0      [virtual void android::VideoControllerWrap::OnRemoteVideoStateChanged(const wchar_t*, oovoo::sdk::RemoteVideoState, int, int, oovoo::sdk::sdk_error)]
08-10 00:08:23.191  14041-14061/com.oovoo.sdk.oovoosdksampleshow D/ooVooSdkNative﹕ [Debug] 2015-08-10 00:08:23.205 VideoControllerWrap -> OnRemoteVideoStateChanged states not find!      [virtual void android::VideoControllerWrap::OnRemoteVideoStateChanged(const wchar_t*, oovoo::sdk::RemoteVideoState, int, int, oovoo::sdk::sdk_error)]
08-10 00:08:23.281  14041-14061/? D/ooVooSdkNative﹕ [Debug] 2015-08-10 00:08:23.297 Network Reliability:  jitter = 0 RTT = 40 Packetloss = 0 Quality:4      [void oovoo::AvsClient::OnNetworkReliabilityTimer()]
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> initCamera  failed = java.lang.RuntimeException: Fail to connect to camera service
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at -2, native_setup
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 389, <init>
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 339, open
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at -1, initCamera
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at -1, create_and_start_camera
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at -1, cameraResumed
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at -1, onResumed
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at -2, onSurfaceCreated
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at -1, surfaceCreated
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 572, updateWindow
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 86, access$000
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 175, onPreDraw
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 847, dispatchOnPreDraw
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 1919, performTraversals
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 1047, doTraversal
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 5896, run
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 761, run
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 574, doCallbacks
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 544, doFrame
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 747, run
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 733, handleCallback
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 95, dispatchMessage
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 136, loop
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 5105, main
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at -2, invokeNative
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 515, invoke
08-10 00:08:23.381  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 792, run
08-10 00:08:23.391  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at 608, main
08-10 00:08:23.391  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> stack  = at -2, main
08-10 00:08:23.391  14041-14041/? W/System.err﹕ at com.oovoo.core.media.ooVooCamera.initCamera(Unknown Source)
08-10 00:08:23.391  14041-14041/? W/System.err﹕ at com.oovoo.core.media.ooVooCamera.create_and_start_camera(Unknown Source)
08-10 00:08:23.391  14041-14041/? W/System.err﹕ at com.oovoo.core.media.ooVooCamera.cameraResumed(Unknown Source)
08-10 00:08:23.391  14041-14041/? W/System.err﹕ at com.oovoo.core.media.ooVooCamera.onResumed(Unknown Source)
08-10 00:08:23.391  14041-14041/? W/System.err﹕ at com.oovoo.sdk.api.ui.VideoPanel.onSurfaceCreated(Native Method)
08-10 00:08:23.391  14041-14041/? W/System.err﹕ at com.oovoo.sdk.api.ui.VideoPanel.surfaceCreated(Unknown Source)
08-10 00:08:23.391  14041-14061/? E/ooVooSdkSampleShowApp﹕ [Error] ooVooCamera -> cameraResumed -> create_and_start_camera error, state CameraStopped

**Comment by eakraly** [comment]
Hi @mydoal,
We are aware of this issue. It will be addressed in upcoming release.
Thanks for the report!
