### ISSUE TITLE
Issues not available in docs

### ISSUE THREAD

**Issue by nathansizemore** [oovoodev/Android-SDK-Sample#17]
Have to write this here, because issues are not allowed to be submitted in your documentation repo...

I've got a question about use of conference Id:

In the documentation it is described as the lang default string type. Is there a min or max length the string must/can be, and what is the expected encoding format of the string?

**Comment by eakraly** [comment]
Hi @nathansizemore,
There is no minimal size, maximal size is at 64 chars.
The only requirement is that it should be unique in a way that there is no chance irrelevant users join the conference. Using GUID is good to generate a conference id is a good way.
