### ISSUE TITLE
Invite

### ISSUE THREAD

**Issue by mdiaz78** [oovoodev/Android-SDK-Sample#18]
I'm developing an application based in your sample project (ver 2.2), I have two android smarphones running the apk.

I'm trying to invite one user to my created conference room from one smarphone (room) to the other one(not joining from the other smartphone, this way is done), but i'm not able to do this.

I'm using this code to send  conference message and it always return true

application.sendCNMessage(to, CNMessageType.Call, null)

and when you go step by step

final CNMessage cnMessage = new CNMessage(to, type, conferenceId, displayName,uniqueId)); //parameters are filled correctly.

Could you please help me how to invite a user to my conference room (from the room smartphone) with code please.

Thank you

**Comment by eakraly** [comment]
Hi @mdiaz78 ,
Is this issue still relevant?

**Comment by mdiaz78** [comment]
Hi Pavel

Not any more

Thanks
