### ISSUE TITLE
UnsatisfiedLinkError VideoPanel.attach()

### ISSUE THREAD

**Issue by pawelcala** [oovoodev/Android-SDK-Sample#19]
Hello,
i'm trying to build simple project with your sdk. I'm gettings this error all the time. VideoPanel as well as logic is placed in Fragment. Initialization process is done in onViewCreated. It seems that native libraries are not loaded. Any ideas on how to fix this issue?

`-04 12:52:46.894  2854  2854 E AndroidRuntime: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class com.oovoo.sdk.api.ui.VideoPanel
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at com.futuremind.android.issuestand.fragment.OovooFragment.onCreateView(OovooFragment.java:78)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class com.oovoo.sdk.api.ui.VideoPanel
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	... 15 more
03-04 12:52:46.894  2854  2854 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Native Method)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	... 20 more
03-04 12:52:46.894  2854  2854 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void com.oovoo.sdk.api.ui.VideoPanel.attach() (tried Java_com_oovoo_sdk_api_ui_VideoPanel_attach and Java_com_oovoo_sdk_api_ui_VideoPanel_attach__)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at com.oovoo.sdk.api.ui.VideoPanel.attach(Native Method)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	at com.oovoo.sdk.api.ui.VideoPanel.<init>(Unknown Source)
03-04 12:52:46.894  2854  2854 E AndroidRuntime: 	... 22 more`

**Comment by eakraly** [comment]
Hi @pawelcala 
Is this issue still relevant?

**Comment by pawelcala** [comment]
Hey,
Don't remember now but i think i solved this issue somehow. Thanks
