### ISSUE TITLE
Join conference, but always receive "onJoinSessionError: Error"

### ISSUE THREAD

**Issue by fishtrees** [oovoodev/Android-SDK-Sample#2]
I cloned the oovoo Android-SDK-Sample yesterday, filled my app id and app token into AndroidManifest.xml like this:

```
 <meta-data
            android:name="AppId"
            android:value="\ 12349983351235" />
        <meta-data
            android:name="AppToken"
            android:value="MDAxMDAxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfwcGJcQu%2Fp8X%2FcBCb4yYSORm7g81%2BQdHq1ZCnPqVXGUJ3hjhzUDqV2CBApaVB06OAZtn9lxz34mY9PHB%2FDZPOVLrrye4OI5yac2n%2BHcJjWEMkFxXjr4lvFXrUTdzRMB4%3D" />

```

after that, I launched the app, entered Conference ID: "TEST_SESSION_123", Display Name: "ft", tapped "Join" button, then join failed. always read this log message from logcat:
```
E/com.ooVoo.oovoosample.Main.MainActivity﹕ onJoinSessionError: Error
```

is my app token broken?

**Comment by albert302** [comment]
I'm getting this error on v1.4. Any ideas in how to solve it??
