### ISSUE TITLE
OOVOO SDK sample app Freezing issue

### ISSUE THREAD

**Issue by wingoku** [oovoodev/Android-SDK-Sample#21]
I am using the sample app provided by OOVOO sdk. I am running the app on my Nexus 5 with Marshmallow 6.0.1. 

The Problem:
When the video call is accepted by another user and _AVChatSessionFragment _opens, the app shows _Joining _on the screen and then the app **freezes**. Sometimes the app shows **App Not Responding dialog** as well. **Logs can be found** [here](https://pastee.org/9456y)

Please help me resolve this issue.

**Comment by eakraly** [comment]
Hi @wingoku 
You need to add disk write permission to manifest of you application
Thanks

**Comment by wingoku** [comment]
I had this permission already added. Anyways I resolved the problem. Btw are you the developer of the sdk?

**Comment by eakraly** [comment]
Yes

**Comment by wingoku** [comment]
@eakraly I am getting this error when the app starts: 

> 
E/ooVooSdkSampleShowApp: [Error] 2016-03-14 15:05:04.606 Application -> Use AVChat only ?  YES 	[void oovoo::sdk::ooVooClientImpl::Init()]

 Login error with description 

> Error Unknown (37)

Any ideas how to resolve it?
