### ISSUE TITLE
UnsatisfiedLinkError: dlopen failed

### ISSUE THREAD

**Issue by AlexandroKurchenko** [oovoodev/Android-SDK-Sample#23]
When i started  on devices what not suport  arm architecture, the app is not responce anymore. Its stops respons on this check:
` if (!ooVooClient.isDeviceSupported()) {`
its not cool  and very annoying. the full log is : 
`04-21 07:04:27.684 2288-2288/com.wonderslab.camcrush I/MultiDex: VM with version 2.1.0 has multidex support
04-21 07:04:27.684 2288-2288/com.wonderslab.camcrush I/MultiDex: install
04-21 07:04:27.684 2288-2288/com.wonderslab.camcrush I/MultiDex: VM has multidex support, MultiDex support library is disabled.
04-21 07:04:27.684 2288-2288/com.wonderslab.camcrush I/MultiDex: install
04-21 07:04:27.684 2288-2288/com.wonderslab.camcrush I/MultiDex: VM has multidex support, MultiDex support library is disabled.
04-21 07:04:27.792 2288-2322/com.wonderslab.camcrush I/GMPM: App measurement is starting up
04-21 07:04:27.945 2288-2288/com.wonderslab.camcrush D/AndroidRuntime: Shutting down VM
04-21 07:04:27.946 2288-2288/com.wonderslab.camcrush W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.wonderslab.camcrush-1/lib/x86/libooVooSdk.so: has text relocations
04-21 07:04:27.946 2288-2288/com.wonderslab.camcrush W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:372)
04-21 07:04:27.946 2288-2288/com.wonderslab.camcrush W/System.err:     at java.lang.System.loadLibrary(System.java:1076)
04-21 07:04:27.946 2288-2288/com.wonderslab.camcrush W/System.err:     at com.oovoo.sdk.api.ooVooClientImpl.<clinit>(Unknown Source)
04-21 07:04:27.946 2288-2288/com.wonderslab.camcrush W/System.err:     at com.wonderslab.camcrush.utils.ovoo.ooVooSdkApp.onCreate(ooVooSdkApp.java:117)
04-21 07:04:27.946 2288-2288/com.wonderslab.camcrush W/System.err:     at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:326)
04-21 07:04:27.946 2288-2288/com.wonderslab.camcrush W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
04-21 07:04:27.946 2288-2288/com.wonderslab.camcrush W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
04-21 07:04:27.946 2288-2288/com.wonderslab.camcrush W/System.err:     at android.app.ActivityThread.-wrap1(ActivityThread.java)
04-21 07:04:27.946 2288-2288/com.wonderslab.camcrush W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
04-21 07:04:27.946 2288-2288/com.wonderslab.camcrush W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-21 07:04:27.946 2288-2288/com.wonderslab.camcrush W/System.err:     at android.os.Looper.loop(Looper.java:148)
04-21 07:04:27.946 2288-2288/com.wonderslab.camcrush W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
04-21 07:04:27.946 2288-2288/com.wonderslab.camcrush W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-21 07:04:27.946 2288-2288/com.wonderslab.camcrush W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-21 07:04:27.946 2288-2288/com.wonderslab.camcrush W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

Its heppens on emulators which in android studio and genymotion, because i am don`t have this devices on hands (Test on Samsung galaxy s6 with android 6.0, Nexus 5 and 5X  with android 6.0).

**Comment by eakraly** [comment]
Hi @AlexandroKurchenko 
We are about to release new version of SDK in a few days - which will solve this issue.
Stay tuned!
