### ISSUE TITLE
NDK build error

### ISSUE THREAD

**Issue by noman404** [oovoodev/Android-SDK-Sample#24]
I have entered the path of my ndk but it shows MY_PATH/ndk-build failed.

**Comment by eakraly** [comment]
Hi @noman404 ,
Please provide more details about your setup so we can help you.
What OS are you using, where do you specify MY_PATH and how exactly are you using it.

**Comment by noman404** [comment]
I am using Windows 10 and i put the ndk at D:\ drive and added it to environment variable also. After finishing the Gradle build it shows that error.

**Comment by nikunjgundaniya** [comment]
commandLine ndkDir + '/ndk-build.cmd' worked for me.

**Comment by bhavikmehta5491** [comment]
@nikunjgundaniya : can you please guide me, i am facing the same issue...

**Comment by nikunjgundaniya** [comment]
@bhavikmehta5491 

`task ndkBuild(type: Exec, description: "Task to run ndk-build") {`
`Properties properties = new Properties()`
`properties.load(project.rootProject.file('local.properties').newDataInputStream())`
`def ndkDir = properties.getProperty('ndk.dir')`
`commandLine ndkDir + '/ndk-build.cmd'`
`}`

try this!
