### ISSUE TITLE
Unable to add AppId and App Token

### ISSUE THREAD

**Issue by RajanKochhar** [oovoodev/Android-SDK-Sample#3]
Hi,

I am not able to start the sample app and it gives me error that APPID is invalid.
I created AppId and token through developer console and put it in manifest file.

AppId : 12349983351285
Active Token: MDAxMDAxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACOcJui%2BgjAXE3b0enshz%2FdIB9W4FTeaYjG4HDgRW5lOs0UsL8Ezbcrgx6WvIw8hDXn2jHB9kbt%2BJP6Vs%2B%2BIFPFFj4pwDUbKXF%2Fr99VdCyLyTQ2XrMPjYbfLI9raXzOu335GyPON%2B8zglmaig3%2FS6q%2B

Also in a personal project, initSDK gives error invalid parameter. I do not find enough details on this.

**Comment by eakraly** [comment]
Hi @JASVIJI,
You need to sign commercial agreement with ooVoo in order to get the logo removed.

Thank
