### ISSUE TITLE
Apk Size Increases.

### ISSUE THREAD

**Issue by sandy8137** [oovoodev/Android-SDK-Sample#35]
After using your SDK my apk size drastically increases up to 16 MB. am  i doing something wrong?and please tell me that how can i decrease that Size. if not then why should i use your SDK at all?

**Comment by sandy8137** [comment]
hmm..this is unfair to close thread without saying a word.if u have a product ,and i am facing some serious problems with that one,then it's your responsibility to help me out.

we are using it for all platforms, but now you showing me a exit door.Great help Mate.Keep it UP.

**Comment by eakraly** [comment]
Increase in APK size is expected. This is what is required to provide video conferencing functionality for 2 platforms (x86 and arm).
Obviously, you are free to choose and consider other platforms.
