### ISSUE TITLE
Custom VideoPanel issue

### ISSUE THREAD

**Issue by NehaKushwah993** [oovoodev/Android-SDK-Sample#36]
Hi, I am running oovoo Sample App for Android, But when I am establishing VideoCall between 2 persons then after 10-15 minutes its automatically closing app because of RAM issue. 

I observed my Android’s RAM(free space) is continuously decreasing very quickly while in VideoCall.

Please find log in TRACE Mode : 07-28 12:54:26.174 15912-15958/com.oovoo.sdk.oovoosdksampleshow V/ooVooSdkNative: [Trace] 2016-07-28 12:54:26.183 HTTP Request name:sso/app/login URL: https://connect.sandbox.oovoo.com/1.0/sso/app/login?at=************************************************************************************************************************************************************************************************************&amp;ct=Android&amp;cst=Phone&amp;sv=2.3.0.113&amp;cv=2.3.0.117[bool oovoo::sdk::webservice::request::Prepare()]07-28 12:54:26.174 15912-15958/com.oovoo.sdk.oovoosdksampleshow V/ooVooSdkNative: [Trace] 2016-07-28 12:54:26.183 HTTP Request body = { &quot;payload&quot;: { &quot;user_id&quot;: &quot;1234567&quot; } }[bool oovoo::sdk::webservice::request::Prepare()]07-28 12:54:28.344 15912-15958/com.oovoo.sdk.oovoosdksampleshow V/ooVooSdkNative: [Trace] 2016-07-28 12:54:28.350 LoginSDK ML -&gt;[oovoo::sdk::AccountImpl::LoginAccount(const wchar_t*, oovoo::sdk::OnOoVooSdkResult)::&lt;lambda(oovoo::sdk::response_ptr)&gt;]07-28 12:54:28.354 15912-15958/com.oovoo.sdk.oovoosdksampleshow V/ooVooSdkNative: [Trace] 2016-07-28 12:54:28.353 LoginSDK ML &lt;-[oovoo::sdk::AccountImpl::LoginAccount(const wchar_t*, oovoo::sdk::OnOoVooSdkResult)::&lt;lambda(oovoo::sdk::response_ptr)&gt;]07-28 12:54:28.374 15912-15912/com.oovoo.sdk.oovoosdksampleshow I/dalvikvm: Could not find method android.app.Notification$Builder.setLocalOnly, referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zza07-28 12:54:28.374 15912-15912/com.oovoo.sdk.oovoosdksampleshow W/dalvikvm: VFY: unable to resolve virtual method 210: Landroid/app/Notification$Builder;.setLocalOnly (Z)Landroid/app/Notification$Builder;07-28 12:54:28.374 15912-15912/com.oovoo.sdk.oovoosdksampleshow D/dalvikvm: VFY: replacing opcode 0x6e at 0x00c807-28 12:54:37.254 15912-15958/com.oovoo.sdk.oovoosdksampleshow V/ooVooSdkNative: [Trace] 2016-07-28 12:54:37.261 plugin: looking for info, device Id &lt;core_factory:2.3.0.113:video_capture (1):1&gt; num of plugins: 0/19[oovoo::sdk::plugin_info::ptr oovoo::plugin_manager::GetPluginInfo(const string&amp;)]07-28 12:54:37.254 15912-15958/com.oovoo.sdk.oovoosdksampleshow V/ooVooSdkNative: [Trace] 2016-07-28 12:54:37.261 plugin: found. device Id &lt;core_factory:2.3.0.113:video_capture (1):1&gt; plugin found: Plugin id &lt;1&gt; name &lt;FRONT&gt; type &lt;video_capture (1)&gt; state &lt;not_created&gt; full id &lt;core_factory:2.3.0.113:video_capture (1):1&gt; is default &lt;1&gt; parameters &lt;{}&gt; category &lt;video_device&gt; [oovoo::sdk::plugin_info::ptr oovoo::plugin_manager::GetPluginInfo(const string&amp;)]07-28 12:54:37.254 15912-15912/com.oovoo.sdk.oovoosdksampleshow V/JniWrapperBase: try to create object of class &lt;java/util/ArrayList&gt; ...07-28 12:54:37.254 15912-15958/com.oovoo.sdk.oovoosdksampleshow V/ooVooSdkNative: [Trace] 2016-07-28 12:54:37.264 plugin: looking for info, device Id &lt;core_factory:2.3.0.113:video_capture (1):0&gt; num of plugins: 0/19[oovoo::sdk::plugin_info::ptr oovoo::plugin_manager::GetPluginInfo(const string&amp;)]07-28 12:54:37.254 15912-15958/com.oovoo.sdk.oovoosdksampleshow V/ooVooSdkNative: [Trace] 2016-07-28 12:54:37.264 plugin: found. device Id &lt;core_factory:2.3.0.113:video_capture (1):0&gt; plugin found: Plugin id &lt;0&gt; name &lt;BACK&gt; type &lt;video_capture (1)&gt; state &lt;not_created&gt; full id &lt;core_factory:2.3.0.113:video_capture (1):0&gt; is default &lt;0&gt; parameters &lt;{}&gt; category &lt;video_device&gt; [oovoo::sdk::plugin_info::ptr oovoo::plugin_manager::GetPluginInfo(const string&amp;)]07-28 12:54:37.254 15912-15958/com.oovoo.sdk.oovoosdksampleshow V/ooVooSdkNative: [Trace] 2016-07-28 12:54:37.264 plugin: looking for info, device Id &lt;core_factory:2.3.0.113:video_capture (1):1&amp;amp;gt; num of plugins: 0/19[oovoo::sdk::plugin_info::ptr oovoo::plugin_manager::GetPluginInfo(const string&amp;amp;amp;)]07-28 12:54:37.264 15912-15958/com.oovoo.sdk.oovoosdksampleshow V/ooVooSdkNative: [Trace] 2016-07-28 12:54:37.264 plugin: found. device Id &amp;amp;lt;core_factory:2.3.0.113:video_capture (1):1&amp;amp;gt; plugin found: Plugin id &amp;amp;lt;1&amp;amp;gt; name &amp;amp;lt;FRONT&amp;amp;gt; type &amp;amp;lt;video_capture (1)&amp;amp;gt; state &amp;amp;lt;not_created&amp;amp;gt; full id &amp;amp;lt;core_factory:2.3.0.113:video_capture (1):1&amp;amp;gt; is default &amp;amp;lt;1&amp;amp;gt; parameters &amp;amp;lt;{}&amp;amp;gt; category &amp;amp;lt;video_device&amp;amp;gt; [oovoo::sdk::plugin_info::ptr oovoo::plugin_manager::GetPluginInfo(const string&amp;amp;amp;)]07-28 12:54:37.264 15912-15958/com.oovoo.sdk.oovoosdksampleshow V/ooVooSdkNative: [Trace] 2016-07-28 12:54:37.265 try to create object of class &amp;amp;lt;java/util/ArrayList&amp;amp;gt; ... [static _jobject* oovoo::android::JniWrapperBase::create_jobject(JNIEnv*, const string&amp;amp;amp;)]07-28 12:54:37.264 15912-15958/com.oovoo.sdk.oovoosdksampleshow V/ooVooSdkNative: [Trace] 2016-07-28 12:54:37.265 create object of class &amp;amp;lt;java/util/ArrayList&amp;amp;gt; done. [static _jobject* oovoo::android::JniWrapperBase::create_jobject(JNIEnv*, const string&amp;amp;amp;)]07-28 12:54:37.264 15912-15958/com.oovoo.sdk.oovoosdksampleshow V/ooVooSdkNative: [Trace] 2016-07-28 12:54:37.268 plugin: looking for info, device Id &amp;amp;lt;core_factory:2.3.0.113:video_capture (1):1&amp;amp;... 

And I am not changing any thing I am using oovooSample after downloading from oovoo as it as. I am changing only the API key nothing else and not changing any files of .so and .jar. let me know solution for this issue.

**Comment by eakraly** [comment]
Custom VideoPanel is an example of how you can build your own VideoPanel - it is not intended for production use. And yes - it has memory leak.

**Comment by NehaKushwah993** [comment]
So this issue couldn't be resolved for future releases?
