### ISSUE TITLE
Could not run ooVooSample on Nexus 7 - 2013

### ISSUE THREAD

**Issue by hoangtu23** [oovoodev/Android-SDK-Sample#6]
I could run sample with my Nexus 5
But it did not work with Nexus 7
Please check below logs:

---------------
03-03 23:20:02.187: D/ooVooSample(31909): setting preview video surface
03-03 23:20:02.192: I/ooVooSample(31909): Surface is not null
03-03 23:20:02.192: D/InternalEventsListener(31909): [Debug] Resume: preview was started false
03-03 23:20:02.195: D/InternalEventsListener(31909): [Debug] raiseOnResume: No preview unit yet!
03-03 23:20:02.195: D/ConferenceManager(31909): [Debug] onResume
03-03 23:20:02.197: D/ParticipantHolder(31909): updating GLview 2131361802 for user null
03-03 23:20:02.202: D/ParticipantHolder(31909): Resume: on_pause=true
03-03 23:20:02.202: D/ooVooSample(31909): ParticipantsManager.getInstance().getParticipants().size() = 1
03-03 23:20:02.202: D/ooVooSample(31909): onResume - participantViewId =2131361802 participantId 
03-03 23:20:02.206: D/ooVooSdkNative(31909): [Debug] nCreate calls convertJStringToCharPtr renderer env= 0xb5051240	[jlong Java_com_oovoo_core_ClientCore_VideoChannelPtr_nCreate(JNIEnv*, jobject, jstring)]
03-03 23:20:02.210: D/ooVooSample(31909): Turn camera to: true
03-03 23:20:02.213: D/ConferenceCore(31909): [Debug] Display orientation: 0
03-03 23:20:02.217: D/InternalEventsListener(31909): [Debug] InternalEventsListener::OnCameraTurnedOn with channell address: 0 err = InvalidParameter camera resolution 0x0 FPS = 0
03-03 23:20:02.221: D/ooVooSample(31909): received OnCameraUnmuted (JAVA) error = InvalidParameter
03-03 23:20:02.223: E/InternalEventsListener(31909): [Error] InternalEventsListener::OnCameraTurnedOn preview unit is null, errorCode = InvalidParameter
03-03 23:20:02.228: I/ooVooSdkNative(31909): [Info] ConferenceCoreEventsHandler::OnCameraTurnedOn: rc = Invalid Parameter channelJniPtr = 0 FrameSize = 0x0 FPS = 0	[virtual void ooVoo::android::ConferenceCoreEventsHandler::OnCameraTurnedOn(ooVoo::ConferenceCoreError, ooVoo::IVideoOutConductor::ptr, const ooVoo::FrameSize&, int)]
03-03 23:20:02.235: W/ConferenceCore(31909): [Warning] turnMyVideoOn: use default camera
03-03 23:20:02.237: D/ConferenceCore(31909): [Debug] GetMediaDeviceList: there are 0 devices found of type Camera
03-03 23:20:02.240: D/ConferenceCore(31909): [Debug] GetMediaDevice: looking for device id -1 in Camera list of 0 items
03-03 23:20:02.244: W/ConferenceCore(31909): [Warning] GetMediaDevice: Not Found device id -1 in Camera list of 0 items
03-03 23:20:02.247: A/libc(31909): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x38 in tid 31952 (Thread-774)
03-03 23:20:02.251: E/ConferenceCore(31909): [Error] Select camera failed No configuration available for camera -1 device
03-03 23:20:02.253: D/VideoRenderer(31909): [Debug] onSurfaceChanged resolution 1116x1238
03-03 23:20:02.258: D/VideoRenderer(31909): [Debug] onSurfaceChanged resolution 1116x1238 owner aspect: 0.901454
03-03 23:20:02.262: D/ooVooSdkNative(31909): [Debug] Logo: 74x24 len = 7104	[_jbyteArray* Java_com_oovoo_core_ui_LogoRenderer_loadooVooLogoImage(JNIEnv*, jobject)]
03-03 23:20:02.300: E/AndroidRuntime(31909): FATAL EXCEPTION: GLThread 771
03-03 23:20:02.300: E/AndroidRuntime(31909): Process: com.ooVoo.oovoosample, PID: 31909
03-03 23:20:02.300: E/AndroidRuntime(31909): java.lang.ClassCastException: com.ooVoo.oovoosample.Common.OoVooSampleApplication cannot be cast to android.app.Activity
03-03 23:20:02.300: E/AndroidRuntime(31909): 	at com.oovoo.core.ConferenceCore.isTablet(ConferenceCore.java:1261)
03-03 23:20:02.300: E/AndroidRuntime(31909): 	at com.oovoo.core.ui.VideoRenderer.render(VideoRenderer.java:191)
03-03 23:20:02.300: E/AndroidRuntime(31909): 	at com.oovoo.core.ui.VideoRenderer.onDrawFrame(VideoRenderer.java:164)
03-03 23:20:02.300: E/AndroidRuntime(31909): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
03-03 23:20:02.300: E/AndroidRuntime(31909): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
---------------

**Comment by eakraly** [comment]
Please try our new release 2.0
