### ISSUE TITLE
INIT CONFERENCE FAILED (SERVER ADDRESS NOT VALID)

### ISSUE THREAD

**Issue by saivirinchi** [oovoodev/Android-SDK-Sample#9]
Hi i tested your demo app that comes with your oovoo sdk zip file and i tested in my emulator but it gives an error as ServerAddressNotValid

**Comment by eranmalovany** [comment]
can you make sure internet access is enabled.

**Comment by saivirinchi** [comment]
ya internet is enabled

**Comment by saivirinchi** [comment]
If iam using my own app id and app token and if i install in mobile it says error as not authorized....

**Comment by eranmalovany** [comment]
ok, so the error is different now, can you try please running the init transaction with App ID and token on your web browser to see if you are getting results.

**Comment by saivirinchi** [comment]
YA ITS WORKING
